/*
 * config.h - Configuration for GNU nano 8.3 on LikeOS
 *
 * Hand-crafted for the LikeOS port.
 * Based on config.h.in from nano-8.3 tarball.
 */

#ifndef _CONFIG_H
#define _CONFIG_H

/* Mark that config.h has been included (gnulib attribute.h checks this) */
#define _GL_CONFIG_H_INCLUDED 1

/* Ensure stdbool.h is available everywhere after config.h */
#include <stdbool.h>

/* gnulib attribute macros - normally generated by gnulib build system */
#if __GNUC__ >= 7 || __has_attribute(__fallthrough__)
# define _GL_ATTRIBUTE_FALLTHROUGH __attribute__ ((__fallthrough__))
#else
# define _GL_ATTRIBUTE_FALLTHROUGH ((void)0)
#endif

#define _GL_ATTRIBUTE_PURE        __attribute__ ((__pure__))
#define _GL_ATTRIBUTE_CONST       __attribute__ ((__const__))
#define _GL_ATTRIBUTE_MALLOC      __attribute__ ((__malloc__))
#define _GL_ATTRIBUTE_NOINLINE    __attribute__ ((__noinline__))
#define _GL_ATTRIBUTE_NONNULL(x)  __attribute__ ((__nonnull__ x))
#define _GL_ATTRIBUTE_UNUSED      __attribute__ ((__unused__))
#define _GL_ATTRIBUTE_MAYBE_UNUSED __attribute__ ((__unused__))
#define _GL_ATTRIBUTE_NODISCARD   __attribute__ ((__warn_unused_result__))
#define _GL_ATTRIBUTE_RETURNS_NONNULL __attribute__ ((__returns_nonnull__))
#define _GL_ATTRIBUTE_FORMAT(spec) __attribute__ ((__format__ spec))
#define _GL_ATTRIBUTE_SENTINEL(pos)
#define _GL_ATTRIBUTE_PACKED      __attribute__ ((__packed__))
#define _GL_ATTRIBUTE_COLD        __attribute__ ((__cold__))
#define _GL_ATTRIBUTE_NONSTRING
#define _GL_ATTRIBUTE_NOTHROW     __attribute__ ((__nothrow__))
#define _GL_ATTRIBUTE_LEAF        __attribute__ ((__leaf__))
#define _GL_ATTRIBUTE_MAY_ALIAS   __attribute__ ((__may_alias__))
#define _GL_ATTRIBUTE_DEPRECATED
#define _GL_ATTRIBUTE_DEALLOC(f, i)
#define _GL_ATTRIBUTE_DEALLOC_FREE
#define _GL_ATTRIBUTE_REPRODUCIBLE
#define _GL_ATTRIBUTE_UNSEQUENCED

/* Package information */
#define PACKAGE "nano"
#define PACKAGE_NAME "GNU nano"
#define PACKAGE_VERSION "8.3"
#define PACKAGE_STRING "GNU nano 8.3"
#define PACKAGE_TARNAME "nano"
#define PACKAGE_URL "https://nano-editor.org"
#define PACKAGE_BUGREPORT "nano-devel@gnu.org"
#define VERSION "8.3"

/* Paths */
#define SYSCONFDIR "/etc"

/* Regex flag(s) for extended regular expressions */
#define NANO_REG_EXTENDED REG_EXTENDED

/* ===== Feature toggles ===== */
/* Enable core editing features */
#define ENABLE_COLOR      1
#define ENABLE_COMMENT    1
#define ENABLE_HELP       1
#define ENABLE_HISTORIES  1
#define ENABLE_JUSTIFY    1
#define ENABLE_LINENUMBERS 1
#define ENABLE_MULTIBUFFER 1
#define ENABLE_NANORC     1
#define ENABLE_OPERATINGDIR 1
#define ENABLE_TABCOMP    1
#define ENABLE_WORDCOMPLETION 1
#define ENABLE_WRAPPING   1
#define ENABLE_BROWSER    1

/* Disable features requiring unavailable dependencies or complex syscalls */
/* #undef ENABLE_EXTRA */        /* Easter egg - not needed */
/* #undef ENABLE_FORMATTER */    /* External formatter - needs complex pipe/fork */
/* #undef ENABLE_LINTER */       /* External linter - needs complex pipe/fork */
/* #undef ENABLE_MOUSE */        /* Mouse support - our ncurses supports it, enable it */
#define ENABLE_MOUSE      1
/* #undef ENABLE_NLS */          /* No i18n support */
#define ENABLE_SPELLER    1      /* External spell checker */
/* #undef ENABLE_UTF8 */         /* No wide character support yet */

/* ===== Standard headers ===== */
#define HAVE_LIMITS_H     1
#define HAVE_STDINT_H     1
#define HAVE_STDIO_H      1
#define HAVE_STDLIB_H     1
#define HAVE_STRING_H     1
#define HAVE_STRINGS_H    1
#define HAVE_UNISTD_H     1
#define HAVE_STDBOOL_H    1
#define HAVE_DIRENT_H     1
#define HAVE_FCNTL        1
#define HAVE_TERMIOS_H    1
#define HAVE_SYS_STAT_H   1
#define HAVE_SYS_TYPES_H  1
#define HAVE_SYS_WAIT_H   1
#define HAVE_SYS_PARAM_H  1
#define HAVE_SIGNAL_H     1
#define HAVE_SCHED_H      1
#define HAVE_PTHREAD_H    1
#define HAVE_PWD_H        1
#define HAVE_FNMATCH_H    1
#define HAVE_FNMATCH      1
#define HAVE_WCHAR_H      1
#define HAVE_WCTYPE_H     1
#define HAVE_LANGINFO_H   1

/* ncurses */
/* #undef HAVE_NCURSESW_NCURSES_H */
#define HAVE_NCURSES_H    1
#define HAVE_CURSES_H     1
#define HAVE_USE_DEFAULT_COLORS 1
#define HAVE_SET_ESCDELAY  1
#define HAVE_KEY_DEFINED   1

/* ===== POSIX functions ===== */
#define HAVE_CHMOD         1
#define HAVE_CHOWN         1
#define HAVE_FCHMOD        1
#define HAVE_FCHOWN        1
#define HAVE_CLOSEDIR      1
#define HAVE_OPENDIR       1
#define HAVE_READDIR       1
#define HAVE_FORK          1
#define HAVE_PIPE          1
#define HAVE_WAIT          1
#define HAVE_WAITPID       1
#define HAVE_READLINK      1
#define HAVE_REALPATH      1
#define HAVE_LSTAT         1
#define HAVE_SNPRINTF      1
#define HAVE_VSNPRINTF     1
#define HAVE_FACCESSAT     1
#define HAVE_SIGACTION     1
#define HAVE_RAISE         1

/* ===== C types and features ===== */
#define HAVE_LONG_LONG_INT        1
#define HAVE_UNSIGNED_LONG_LONG_INT 1
#define HAVE_C_VARARRAYS          1
#define HAVE___BUILTIN_EXPECT     1

/* Declarations */
#define HAVE_DECL_SNPRINTF       1
#define HAVE_DECL_VSNPRINTF      1
#define HAVE_DECL_STRNCASECMP    1
#define HAVE_DECL_STRDUP         1
#define HAVE_DECL_STRNLEN        0
#define HAVE_DECL_GETLINE        0
#define HAVE_DECL_GETDELIM       0
#define HAVE_DECL_ISBLANK        0
#define HAVE_DECL_MBRTOWC        1
#define HAVE_DECL_MBSINIT        1
#define HAVE_DECL_WCRTOMB        1
#define HAVE_DECL_WCWIDTH        1
#define HAVE_DECL_TOWLOWER       1
#define HAVE_DECL_ISWBLANK       1
#define HAVE_DECL_DIRFD          0
#define HAVE_DECL_GETC_UNLOCKED  0
#define HAVE_DECL_MEMRCHR        0
#define HAVE_DECL_STRERROR_R     0
#define HAVE_DECL_COPYSIGN       0
#define HAVE_DECL_COPYSIGNF      0
#define HAVE_DECL_COPYSIGNL      0
#define HAVE_DECL_FCHDIR         0
#define HAVE_DECL_ALARM          0
#define HAVE_DECL_GETDTABLESIZE  0
#define HAVE_DECL_GETLOGIN       0
#define HAVE_DECL_GETLOGIN_R     0
#define HAVE_DECL_PROGRAM_INVOCATION_NAME 0
#define HAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME 0

/* wchar/wctype functions */
#define HAVE_MBRTOWC       1
#define HAVE_MBSINIT       1
#define HAVE_WCRTOMB       1
#define HAVE_WCSLEN        1
#define HAVE_WCWIDTH       1
#define HAVE_TOWLOWER      1
#define HAVE_ISWALPHA      1
#define HAVE_ISWBLANK      1
#define HAVE_ISWCNTRL      1
#define HAVE_ISWCTYPE      1
#define HAVE_ISWPUNCT      1
#define HAVE_MBTOWC        1
#define HAVE_WCTOMB        1
#define HAVE_MBSTOWCS      1
#define HAVE_BTOWC         1
#define HAVE_MBSTATE_T     1
#define HAVE_WINT_T        1

/* Missing functions (provided by gnulib) */
#define HAVE_GETLINE      1
#define HAVE_GETDELIM     1
#define HAVE_STRNLEN      1
/* #undef HAVE_STRCASECMP */
#define HAVE_STRNCASECMP   1
#define HAVE_STRCASESTR   1
#define HAVE_MKSTEMPS     1
/* #undef HAVE_CANONICALIZE_FILE_NAME */
/* #undef HAVE_NL_LANGINFO */
/* #undef HAVE_LANGINFO_CODESET */
/* #undef HAVE_MEMRCHR */
/* #undef HAVE_RAWMEMCHR */
/* #undef HAVE_MEMPCPY */
/* #undef HAVE_ALLOCA_H */
/* #undef HAVE_ALLOCA */
/* #undef HAVE_DIRFD */
/* #undef HAVE_ERROR */
/* #undef HAVE_ERROR_H */

/* POSIX features not available */
/* #undef HAVE_GLOB */
/* #undef HAVE_GLOB_H */
/* #undef HAVE_GLOB_PATTERN_P */
/* #undef HAVE_OPENAT */
/* #undef HAVE_LUTIMENS */
/* #undef HAVE_UTIMENSAT */
/* #undef HAVE_UTIME */
/* #undef HAVE_UTIME_H */
/* #undef HAVE_SYS_MMAN_H */
/* #undef HAVE_MPROTECT */
/* #undef HAVE_MAP_ANONYMOUS */
/* #undef HAVE_SIGALTSTACK */
/* #undef HAVE_SIGINTERRUPT */
/* #undef HAVE_SYS_VT_H */
/* #undef HAVE_LIBMAGIC */
/* #undef HAVE_LIBZ */
/* #undef HAVE_MAGIC_H */
/* #undef HAVE_ZLIB_H */

/* Memory allocation */
#define HAVE_MALLOC_POSIX  1
#define HAVE_MALLOC_0_NONNULL 1
#define HAVE_REALLOC_0_NONNULL 1
/* #undef HAVE_FREE_POSIX */

/* Type sizes */
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_LONG_LONG 8

/* Size types - provided by libc's sys/types.h */
/* ssize_t, mode_t, nlink_t, pid_t, uid_t, gid_t are all in sys/types.h */

/* Struct dirent has d_type */
#define HAVE_STRUCT_DIRENT_D_TYPE 1

/* stat time fields */
/* #undef HAVE_STRUCT_STAT_ST_ATIM_TV_NSEC */
/* #undef HAVE_STRUCT_STAT_ST_ATIMENSEC */
/* #undef HAVE_STRUCT_STAT_ST_ATIMESPEC_TV_NSEC */

/* snprintf conformance */
#define HAVE_SNPRINTF_RETVAL_C99    1
#define HAVE_SNPRINTF_TRUNCATION_C99 1

/* restrict keyword */
#define restrict __restrict__

/* inline */
#ifndef __cplusplus
/* inline is available in gcc */
#endif

/* _Noreturn */
#ifndef _Noreturn
#define _Noreturn __attribute__((__noreturn__))
#endif

/* Gnulib needs */
/* #undef NEED_PRINTF_DIRECTIVE_A */
/* #undef NEED_PRINTF_DIRECTIVE_B */
/* #undef NEED_PRINTF_DIRECTIVE_F */
/* #undef NEED_PRINTF_DIRECTIVE_LC */
/* #undef NEED_PRINTF_DIRECTIVE_LS */
/* #undef NEED_PRINTF_DOUBLE */
/* #undef NEED_PRINTF_ENOMEM */
/* #undef NEED_PRINTF_FLAG_GROUPING */
/* #undef NEED_PRINTF_FLAG_LEFTADJUST */
/* #undef NEED_PRINTF_FLAG_ZERO */
/* #undef NEED_PRINTF_INFINITE_DOUBLE */
/* #undef NEED_PRINTF_INFINITE_LONG_DOUBLE */
/* #undef NEED_PRINTF_LONG_DOUBLE */
/* #undef NEED_PRINTF_UNBOUNDED_PRECISION */
/* #undef NEED_PRINTF_FLAG_ALT_PRECISION_ZERO */
/* #undef NEED_SANITIZED_REALLOC */
/* #undef NEED_XOPEN_SOURCE_EXTENDED */

/* Attribute macros */
#define _GL_GNUC_PREREQ(major, minor) \
  ((__GNUC__ > (major)) || (__GNUC__ == (major) && __GNUC_MINOR__ >= (minor)))

/* Gnulib stdbool.h */
/* We have native _Bool / bool in gcc */

/* Prevent gnulib from redefining standard functions */
#define _GL_ALREADY_INCLUDING_STDIO_H
#define _GL_ALREADY_INCLUDING_STDLIB_H

/* va_copy */
/* gcc already provides va_copy */

/* Build without gettext */
#define gettext(s) (s)
#define ngettext(s1, s2, n) ((n) == 1 ? (s1) : (s2))
#define bindtextdomain(pkg, dir) ((void)0)
#define textdomain(pkg) ((void)0)

/* No libintl */
/* #undef HAVE_LIBINTL_H */
/* #undef HAVE_DCGETTEXT */

/* Revision info */
#define PLAINBUILD "from tarball"

#endif /* _CONFIG_H */
