// LikeOS -- the Synopsys port PHYs of DG2 (Arc A-series, display version 13).
//
// DG2 drives its five DDIs through Synopsys PHYs rather than the combo
// and Type-C PHYs of the integrated parts.  Each PHY carries its own PLL
// (the "MPLLB"), which takes the place of the shared display PLLs other
// generations route ports to: a port is clocked by programming its own
// PHY's PLL during the mode set and starting it from the port's PLL
// enable word.  The PLL settings are looked up in tables of register
// values validated for each DisplayPort link rate and for the common
// HDMI clocks; an HDMI clock the tables do not list gets settings
// computed from the PHY's characterisation curves.  The transmitter's
// swing and pre-emphasis are three equalisation fields per lane,
// written straight into the PHY.
//
// At display initialisation every PHY runs a calibration and adaptation
// pass, which the driver waits out before using any port; a PHY that
// does not finish is noted and driven anyway.
//
// None of this has run on hardware here; every step reports what it
// found.
//
// Copyright (C) 2026 The LikeOS Project
// SPDX-License-Identifier for the portions derived from Intel's code: MIT
// Portions Copyright (C) 2019-2025 Intel Corporation
// Portions Copyright (C) 2025 Synopsys, Inc.

#include <kernel/dev/gpu/i915/i915_drv.h>
#include <kernel/dev/gpu/i915/i915_reg.h>
#include <kernel/dev/gpu/i915/intel_display.h>
#include <kernel/dev/gpu/i915/intel_snps_phy.h>
#include <kernel/dev/gpu/i915/intel_snps_phy_regs.h>
#include <kernel/hal/lapic.h>
#include <kernel/io/console.h>
#include <kernel/ke/syscall.h>
#include <kernel/mm/memory.h>

/* ---- PLL states ------------------------------------------------------------- */

/* One MPLLB configuration: the port clock it produces (kHz: the DP link
 * rate or the TMDS clock) and the words as they are written. */
struct mpllb_state {
	uint32_t clock;
	uint32_t ref_control;
	uint32_t mpllb_cp;
	uint32_t mpllb_div;
	uint32_t mpllb_div2;
	uint32_t mpllb_fracn1;
	uint32_t mpllb_fracn2;
	uint32_t mpllb_sscen;
	uint32_t mpllb_sscstep;
};

/* DisplayPort link rates, from the 100 MHz reference.  The two 128b/132b
 * rates spread: DisplayPort 2.0 demands a minimum of spread spectrum. */

static const struct mpllb_state dg2_dp_rbr_100 = {
	.clock = 162000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(4) | SNPS_PHY_MPLLB_CP_PROP(20) |
		SNPS_PHY_MPLLB_CP_INT_GS(65) | SNPS_PHY_MPLLB_CP_PROP_GS(127),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(2) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(2) | SNPS_PHY_MPLLB_MULTIPLIER(226),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(5),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(39321) | SNPS_PHY_MPLLB_FRACN_REM(3),
};

static const struct mpllb_state dg2_dp_hbr1_100 = {
	.clock = 270000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(4) | SNPS_PHY_MPLLB_CP_PROP(20) |
		SNPS_PHY_MPLLB_CP_INT_GS(65) | SNPS_PHY_MPLLB_CP_PROP_GS(127),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(1) |
		SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(2) | SNPS_PHY_MPLLB_MULTIPLIER(184),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_DEN(1),
};

static const struct mpllb_state dg2_dp_hbr2_100 = {
	.clock = 540000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(4) | SNPS_PHY_MPLLB_CP_PROP(20) |
		SNPS_PHY_MPLLB_CP_INT_GS(65) | SNPS_PHY_MPLLB_CP_PROP_GS(127),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_V2I(2) |
		SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(2) | SNPS_PHY_MPLLB_MULTIPLIER(184),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_DEN(1),
};

static const struct mpllb_state dg2_dp_hbr3_100 = {
	.clock = 810000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(4) | SNPS_PHY_MPLLB_CP_PROP(19) |
		SNPS_PHY_MPLLB_CP_INT_GS(65) | SNPS_PHY_MPLLB_CP_PROP_GS(127),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_V2I(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(2) | SNPS_PHY_MPLLB_MULTIPLIER(292),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_DEN(1),
};

static const struct mpllb_state dg2_dp_uhbr10_100 = {
	.clock = 1000000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(4) | SNPS_PHY_MPLLB_CP_PROP(21) |
		SNPS_PHY_MPLLB_CP_INT_GS(65) | SNPS_PHY_MPLLB_CP_PROP_GS(127),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_DIV_CLK_EN |
		SNPS_PHY_MPLLB_DIV_MULTIPLIER(8) | SNPS_PHY_MPLLB_PMIX_EN |
		SNPS_PHY_MPLLB_WORD_DIV2_EN | SNPS_PHY_MPLLB_DP2_MODE |
		SNPS_PHY_MPLLB_SHIM_DIV32_CLK_SEL | SNPS_PHY_MPLLB_V2I(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(2) | SNPS_PHY_MPLLB_MULTIPLIER(368),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_DEN(1),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_EN | SNPS_PHY_MPLLB_SSC_PEAK(58982),
	.mpllb_sscstep = SNPS_PHY_MPLLB_SSC_STEPSIZE(76101),
};

static const struct mpllb_state dg2_dp_uhbr13_100 = {
	.clock = 1350000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(5) | SNPS_PHY_MPLLB_CP_PROP(45) |
		SNPS_PHY_MPLLB_CP_INT_GS(65) | SNPS_PHY_MPLLB_CP_PROP_GS(127),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_DIV_CLK_EN |
		SNPS_PHY_MPLLB_DIV_MULTIPLIER(8) | SNPS_PHY_MPLLB_PMIX_EN |
		SNPS_PHY_MPLLB_WORD_DIV2_EN | SNPS_PHY_MPLLB_DP2_MODE | SNPS_PHY_MPLLB_V2I(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(2) | SNPS_PHY_MPLLB_MULTIPLIER(508),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_DEN(1),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_EN | SNPS_PHY_MPLLB_SSC_PEAK(79626),
	.mpllb_sscstep = SNPS_PHY_MPLLB_SSC_STEPSIZE(102737),
};

static const struct mpllb_state *const dg2_dp_100_tables[] = {
	&dg2_dp_rbr_100,
	&dg2_dp_hbr1_100,
	&dg2_dp_hbr2_100,
	&dg2_dp_hbr3_100,
	&dg2_dp_uhbr10_100,
	&dg2_dp_uhbr13_100,
	NULL,
};

/* The extra embedded-panel rates, all with spread spectrum. */

static const struct mpllb_state dg2_edp_r216 = {
	.clock = 216000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(4) | SNPS_PHY_MPLLB_CP_PROP(19) |
		SNPS_PHY_MPLLB_CP_INT_GS(65) | SNPS_PHY_MPLLB_CP_PROP_GS(127),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(2) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(2) | SNPS_PHY_MPLLB_MULTIPLIER(312),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(5),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(52428) | SNPS_PHY_MPLLB_FRACN_REM(4),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_EN | SNPS_PHY_MPLLB_SSC_PEAK(50961),
	.mpllb_sscstep = SNPS_PHY_MPLLB_SSC_STEPSIZE(65752),
};

static const struct mpllb_state dg2_edp_r243 = {
	.clock = 243000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(4) | SNPS_PHY_MPLLB_CP_PROP(20) |
		SNPS_PHY_MPLLB_CP_INT_GS(65) | SNPS_PHY_MPLLB_CP_PROP_GS(127),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(2) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(2) | SNPS_PHY_MPLLB_MULTIPLIER(356),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(5),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(26214) | SNPS_PHY_MPLLB_FRACN_REM(2),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_EN | SNPS_PHY_MPLLB_SSC_PEAK(57331),
	.mpllb_sscstep = SNPS_PHY_MPLLB_SSC_STEPSIZE(73971),
};

static const struct mpllb_state dg2_edp_r324 = {
	.clock = 324000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(4) | SNPS_PHY_MPLLB_CP_PROP(20) |
		SNPS_PHY_MPLLB_CP_INT_GS(65) | SNPS_PHY_MPLLB_CP_PROP_GS(127),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(1) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(2) | SNPS_PHY_MPLLB_MULTIPLIER(226),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(5),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(39321) | SNPS_PHY_MPLLB_FRACN_REM(3),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_EN | SNPS_PHY_MPLLB_SSC_PEAK(38221),
	.mpllb_sscstep = SNPS_PHY_MPLLB_SSC_STEPSIZE(49314),
};

static const struct mpllb_state dg2_edp_r432 = {
	.clock = 432000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(4) | SNPS_PHY_MPLLB_CP_PROP(19) |
		SNPS_PHY_MPLLB_CP_INT_GS(65) | SNPS_PHY_MPLLB_CP_PROP_GS(127),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(1) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(2) | SNPS_PHY_MPLLB_MULTIPLIER(312),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(5),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(52428) | SNPS_PHY_MPLLB_FRACN_REM(4),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_EN | SNPS_PHY_MPLLB_SSC_PEAK(50961),
	.mpllb_sscstep = SNPS_PHY_MPLLB_SSC_STEPSIZE(65752),
};

static const struct mpllb_state *const dg2_edp_tables[] = {
	&dg2_dp_rbr_100,
	&dg2_edp_r216,
	&dg2_edp_r243,
	&dg2_dp_hbr1_100,
	&dg2_edp_r324,
	&dg2_edp_r432,
	&dg2_dp_hbr2_100,
	&dg2_dp_hbr3_100,
	NULL,
};

/* HDMI TMDS clocks.  Every entry spreads upwards only (the spread
 * itself left off). */

static const struct mpllb_state dg2_hdmi_25_175 = {
	.clock = 25175,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(5) | SNPS_PHY_MPLLB_CP_PROP(15) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(5) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(128) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(143),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(36663) | SNPS_PHY_MPLLB_FRACN_REM(71),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_27_0 = {
	.clock = 27000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(5) | SNPS_PHY_MPLLB_CP_PROP(15) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(5) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(140) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(5),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(26214) | SNPS_PHY_MPLLB_FRACN_REM(2),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_74_25 = {
	.clock = 74250,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(4) | SNPS_PHY_MPLLB_CP_PROP(15) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(3) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(86) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(5),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(26214) | SNPS_PHY_MPLLB_FRACN_REM(2),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_148_5 = {
	.clock = 148500,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(4) | SNPS_PHY_MPLLB_CP_PROP(15) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(2) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(86) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(5),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(26214) | SNPS_PHY_MPLLB_FRACN_REM(2),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_25200 = {
	.clock = 25200,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(7) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(5) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(0),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(128) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(41943) | SNPS_PHY_MPLLB_FRACN_REM(2621),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_27027 = {
	.clock = 27027,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(5) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(0),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(140) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(31876) | SNPS_PHY_MPLLB_FRACN_REM(46555),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_28320 = {
	.clock = 28320,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(5) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(0),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(148) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(40894) | SNPS_PHY_MPLLB_FRACN_REM(30408),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_30240 = {
	.clock = 30240,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(5) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(0),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(160) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(50331) | SNPS_PHY_MPLLB_FRACN_REM(42466),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_31500 = {
	.clock = 31500,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(7) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(4) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(68) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(26214) | SNPS_PHY_MPLLB_FRACN_REM(26214),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_36000 = {
	.clock = 36000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(4) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(82) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(39321) | SNPS_PHY_MPLLB_FRACN_REM(39320),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_40000 = {
	.clock = 40000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(4) |
		SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(96) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(0) | SNPS_PHY_MPLLB_FRACN_REM(0),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_49500 = {
	.clock = 49500,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(4) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(1),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(126) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(13107) | SNPS_PHY_MPLLB_FRACN_REM(13107),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_50000 = {
	.clock = 50000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(4) |
		SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(1),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(128) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(0) | SNPS_PHY_MPLLB_FRACN_REM(0),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_57284 = {
	.clock = 57284,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(4) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(0),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(150) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(42886) | SNPS_PHY_MPLLB_FRACN_REM(49701),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_58000 = {
	.clock = 58000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(4) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(0),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(152) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(52428) | SNPS_PHY_MPLLB_FRACN_REM(52427),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_65000 = {
	.clock = 65000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(7) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(3) |
		SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(72) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(0) | SNPS_PHY_MPLLB_FRACN_REM(0),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_71000 = {
	.clock = 71000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(3) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(80) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(52428) | SNPS_PHY_MPLLB_FRACN_REM(52427),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_74176 = {
	.clock = 74176,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(3) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(86) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(22334) | SNPS_PHY_MPLLB_FRACN_REM(43829),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_75000 = {
	.clock = 75000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(3) |
		SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(88) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(0) | SNPS_PHY_MPLLB_FRACN_REM(0),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_78750 = {
	.clock = 78750,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(3) |
		SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(94) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(0) | SNPS_PHY_MPLLB_FRACN_REM(0),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_85500 = {
	.clock = 85500,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(3) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(104) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(26214) | SNPS_PHY_MPLLB_FRACN_REM(26214),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_88750 = {
	.clock = 88750,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(7) | SNPS_PHY_MPLLB_CP_PROP(15) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(3) |
		SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(1),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(110) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(0) | SNPS_PHY_MPLLB_FRACN_REM(0),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_106500 = {
	.clock = 106500,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(3) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(0),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(138) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(13107) | SNPS_PHY_MPLLB_FRACN_REM(13107),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_108000 = {
	.clock = 108000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(3) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(0),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(140) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(26214) | SNPS_PHY_MPLLB_FRACN_REM(26214),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_115500 = {
	.clock = 115500,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(3) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(0),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(152) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(26214) | SNPS_PHY_MPLLB_FRACN_REM(26214),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_119000 = {
	.clock = 119000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(3) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(0),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(158) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(13107) | SNPS_PHY_MPLLB_FRACN_REM(13107),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_135000 = {
	.clock = 135000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(7) | SNPS_PHY_MPLLB_CP_PROP(15) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(2) |
		SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(76) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(0) | SNPS_PHY_MPLLB_FRACN_REM(0),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_138500 = {
	.clock = 138500,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(2) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(78) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(26214) | SNPS_PHY_MPLLB_FRACN_REM(26214),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_147160 = {
	.clock = 147160,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(2) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(84) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(56623) | SNPS_PHY_MPLLB_FRACN_REM(6815),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_148352 = {
	.clock = 148352,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(2) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(86) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(22334) | SNPS_PHY_MPLLB_FRACN_REM(43829),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_154000 = {
	.clock = 154000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(13) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(2) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(90) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(39321) | SNPS_PHY_MPLLB_FRACN_REM(39320),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_162000 = {
	.clock = 162000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(2) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(96) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(52428) | SNPS_PHY_MPLLB_FRACN_REM(52427),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_209800 = {
	.clock = 209800,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(7) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(2) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(0),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(134) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(60293) | SNPS_PHY_MPLLB_FRACN_REM(7864),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_262750 = {
	.clock = 262750,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(7) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(1) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(72) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(36044) | SNPS_PHY_MPLLB_FRACN_REM(52427),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_267300 = {
	.clock = 267300,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(7) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(1) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(74) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(30146) | SNPS_PHY_MPLLB_FRACN_REM(36699),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_268500 = {
	.clock = 268500,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(7) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(1) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(74) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(45875) | SNPS_PHY_MPLLB_FRACN_REM(13107),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_296703 = {
	.clock = 296703,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(1) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(86) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(22321) | SNPS_PHY_MPLLB_FRACN_REM(36804),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_241500 = {
	.clock = 241500,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(2) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(0),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(160) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(39321) | SNPS_PHY_MPLLB_FRACN_REM(39320),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_319890 = {
	.clock = 319890,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(1) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(2),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(94) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(64094) | SNPS_PHY_MPLLB_FRACN_REM(13631),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_497750 = {
	.clock = 497750,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(15) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(1) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(0),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(166) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(36044) | SNPS_PHY_MPLLB_FRACN_REM(52427),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_592000 = {
	.clock = 592000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(0) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(86) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(13107) | SNPS_PHY_MPLLB_FRACN_REM(13107),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_593407 = {
	.clock = 593407,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(0) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(86) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(22328) | SNPS_PHY_MPLLB_FRACN_REM(7549),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_297 = {
	.clock = 297000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(6) | SNPS_PHY_MPLLB_CP_PROP(14) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_TX_CLK_DIV(1) |
		SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) | SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(86) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(65535),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(26214) | SNPS_PHY_MPLLB_FRACN_REM(26214),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state dg2_hdmi_594 = {
	.clock = 594000,
	.ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(3),
	.mpllb_cp = SNPS_PHY_MPLLB_CP_INT(4) | SNPS_PHY_MPLLB_CP_PROP(15) |
		SNPS_PHY_MPLLB_CP_INT_GS(64) | SNPS_PHY_MPLLB_CP_PROP_GS(124),
	.mpllb_div = SNPS_PHY_MPLLB_DIV5_CLK_EN | SNPS_PHY_MPLLB_PMIX_EN | SNPS_PHY_MPLLB_V2I(2) |
		SNPS_PHY_MPLLB_FREQ_VCO(3),
	.mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(1) | SNPS_PHY_MPLLB_MULTIPLIER(86) |
		SNPS_PHY_MPLLB_HDMI_DIV(1),
	.mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN | SNPS_PHY_MPLLB_FRACN_EN |
		SNPS_PHY_MPLLB_FRACN_DEN(5),
	.mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(26214) | SNPS_PHY_MPLLB_FRACN_REM(2),
	.mpllb_sscen = SNPS_PHY_MPLLB_SSC_UP_SPREAD,
};

static const struct mpllb_state *const dg2_hdmi_tables[] = {
	&dg2_hdmi_25_175,
	&dg2_hdmi_27_0,
	&dg2_hdmi_74_25,
	&dg2_hdmi_148_5,
	&dg2_hdmi_297,
	&dg2_hdmi_594,
	&dg2_hdmi_25200,
	&dg2_hdmi_27027,
	&dg2_hdmi_28320,
	&dg2_hdmi_30240,
	&dg2_hdmi_31500,
	&dg2_hdmi_36000,
	&dg2_hdmi_40000,
	&dg2_hdmi_49500,
	&dg2_hdmi_50000,
	&dg2_hdmi_57284,
	&dg2_hdmi_58000,
	&dg2_hdmi_65000,
	&dg2_hdmi_71000,
	&dg2_hdmi_74176,
	&dg2_hdmi_75000,
	&dg2_hdmi_78750,
	&dg2_hdmi_85500,
	&dg2_hdmi_88750,
	&dg2_hdmi_106500,
	&dg2_hdmi_108000,
	&dg2_hdmi_115500,
	&dg2_hdmi_119000,
	&dg2_hdmi_135000,
	&dg2_hdmi_138500,
	&dg2_hdmi_147160,
	&dg2_hdmi_148352,
	&dg2_hdmi_154000,
	&dg2_hdmi_162000,
	&dg2_hdmi_209800,
	&dg2_hdmi_241500,
	&dg2_hdmi_262750,
	&dg2_hdmi_267300,
	&dg2_hdmi_268500,
	&dg2_hdmi_296703,
	&dg2_hdmi_319890,
	&dg2_hdmi_497750,
	&dg2_hdmi_592000,
	&dg2_hdmi_593407,
	NULL,
};


/* ---- buffer translations ------------------------------------------------------ */

/* One level: the main cursor (swing), and the pre- and post-cursor
 * coefficients of the transmitter equaliser. */
struct snps_trans {
	uint8_t vswing, pre_cursor, post_cursor;
};

/* DisplayPort 1.4 and HDMI, ordered like the DisplayPort levels: 400mV x
 * {0, 3.5, 6, 9.5 dB}, 600mV x {0, 3.5, 6}, 800mV x {0, 3.5}, 1200mV x 0.
 * HDMI takes the last entry by default. */
static const struct snps_trans dg2_snps_trans[] = {
	{ 25, 0, 0 }, /* VS 0, pre-emph 0 */
	{ 32, 0, 6 }, /* VS 0, pre-emph 1 */
	{ 35, 0, 10 }, /* VS 0, pre-emph 2 */
	{ 43, 0, 17 }, /* VS 0, pre-emph 3 */
	{ 35, 0, 0 }, /* VS 1, pre-emph 0 */
	{ 45, 0, 8 }, /* VS 1, pre-emph 1 */
	{ 48, 0, 14 }, /* VS 1, pre-emph 2 */
	{ 47, 0, 0 }, /* VS 2, pre-emph 0 */
	{ 55, 0, 7 }, /* VS 2, pre-emph 1 */
	{ 62, 0, 0 }, /* VS 3, pre-emph 0 */
};
#define DG2_SNPS_TRANS_HDMI_DEFAULT 9

/* DisplayPort 2.0 (128b/132b): the sixteen transmitter presets. */
static const struct snps_trans dg2_snps_trans_uhbr[] = {
	{ 62, 0, 0 }, /* preset 0 */
	{ 55, 0, 7 }, /* preset 1 */
	{ 50, 0, 12 }, /* preset 2 */
	{ 44, 0, 18 }, /* preset 3 */
	{ 35, 0, 21 }, /* preset 4 */
	{ 59, 3, 0 }, /* preset 5 */
	{ 53, 3, 6 }, /* preset 6 */
	{ 48, 3, 11 }, /* preset 7 */
	{ 42, 5, 15 }, /* preset 8 */
	{ 37, 5, 20 }, /* preset 9 */
	{ 56, 6, 0 }, /* preset 10 */
	{ 48, 7, 7 }, /* preset 11 */
	{ 45, 7, 10 }, /* preset 12 */
	{ 39, 8, 15 }, /* preset 13 */
	{ 48, 14, 0 }, /* preset 14 */
	{ 45, 4, 4 }, /* preset 15 */
};

#define ARRAY_LEN(a) ((int)(sizeof(a) / sizeof((a)[0])))

/* ---- per-port state ------------------------------------------------------------ */

struct dg2_port_pll {
	int in_use;
	int is_dp;
	int ssc_asked;
	int lanes;
	uint32_t port_clock;
	struct mpllb_state st;
};

static struct dg2_port_pll dg2_pll[INTEL_MAX_PORTS];
static uint32_t dg2_calib_failed; /* bit per PHY */

int dg2_port_to_phy(int port)
{
	switch (port) {
	case DG2_PORT_A:
		return SNPS_PHY_A;
	case DG2_PORT_B:
		return SNPS_PHY_B;
	case DG2_PORT_C:
		return SNPS_PHY_C;
	case DG2_PORT_D_XELPD:
		return SNPS_PHY_D;
	case DG2_PORT_TC1:
		return SNPS_PHY_E;
	default:
		return -1;
	}
}

int dg2_phy_failed_calibration(int port)
{
	int phy = dg2_port_to_phy(port);
	return phy >= 0 && (dg2_calib_failed & (1u << phy));
}

static int port_ok(int port)
{
	return port >= 0 && port < INTEL_MAX_PORTS && dg2_port_to_phy(port) >= 0;
}

static int output_is_dp(const struct intel_output *o)
{
	return o->type == INTEL_OUTPUT_DP || o->type == INTEL_OUTPUT_EDP;
}

static int dp_is_uhbr(uint32_t rate)
{
	return rate == 1000000 || rate == 1350000 || rate == 2000000;
}

/* Read-modify-write; the write always goes out. */
static uint32_t rmw(struct i915_device *i915, uint32_t reg, uint32_t clear, uint32_t set)
{
	uint32_t old = i915_read32(i915, reg);
	i915_write32(i915, reg, (old & ~clear) | set);
	return old;
}

/* Poll until (reg & mask) == value. */
static int wait_reg(struct i915_device *i915, uint32_t reg, uint32_t mask, uint32_t value,
		    uint32_t timeout_us)
{
	uint32_t step = timeout_us > 2000 ? 10 : 1;

	for (uint32_t t = 0;; t += step) {
		if ((i915_read32(i915, reg) & mask) == value)
			return 0;
		if (t >= timeout_us)
			return -ETIMEDOUT;
		lapic_delay_us(step);
	}
}

/* ---- PLL arithmetic --------------------------------------------------------------- */

static uint64_t div_round_closest_u64(uint64_t x, uint64_t d)
{
	return (x + d / 2) / d;
}

static int clock_matches(uint32_t a, uint32_t b)
{
	return (a > b ? a - b : b - a) <= 1;
}

/* The port clock an MPLLB state produces: the 100 MHz reference over the
 * pre-divider, times the feedback multiplier with its fraction, over ten
 * and the transmitter divider. */
static uint32_t mpllb_port_clock(const struct mpllb_state *s)
{
	uint32_t frac_quot = 0, frac_rem = 0, frac_den = 1;
	uint32_t multiplier, tx_clk_div, refclk = 100000, ref_div;
	uint64_t num;

	ref_div = (s->mpllb_div2 & SNPS_PHY_MPLLB_REF_CLK_DIV_MASK) >> SNPS_PHY_MPLLB_REF_CLK_DIV_SHIFT;
	if (ref_div)
		refclk >>= ref_div - 1;
	if (s->mpllb_fracn1 & SNPS_PHY_MPLLB_FRACN_EN) {
		frac_quot = s->mpllb_fracn2 & SNPS_PHY_MPLLB_FRACN_QUOT_MASK;
		frac_rem = (s->mpllb_fracn2 & SNPS_PHY_MPLLB_FRACN_REM_MASK) >>
			   SNPS_PHY_MPLLB_FRACN_REM_SHIFT;
		frac_den = s->mpllb_fracn1 & SNPS_PHY_MPLLB_FRACN_DEN_MASK;
		if (!frac_den)
			frac_den = 1;
	}
	multiplier = (s->mpllb_div2 & SNPS_PHY_MPLLB_MULTIPLIER_MASK) / 2 + 16;
	tx_clk_div = (s->mpllb_div & SNPS_PHY_MPLLB_TX_CLK_DIV_MASK) >> SNPS_PHY_MPLLB_TX_CLK_DIV_SHIFT;
	num = (uint64_t)refclk * ((multiplier << 16) + frac_quot) +
	      (uint32_t)div_round_closest_u64((uint64_t)refclk * frac_rem, frac_den);
	return (uint32_t)div_round_closest_u64(num, (uint64_t)10 << (tx_clk_div + 16));
}

/* ---- the HDMI PLL, computed ------------------------------------------------------- */

/* For a TMDS clock the tables do not have: the feedback multiplier and
 * fraction for the VCO, and the charge-pump settings interpolated from
 * the PHY vendor's characterisation curves for this PHY.  The arithmetic
 * is kept exactly as the vendor's sequence does it (64-bit fixed point,
 * wrapping where it wraps, the 32-bit divisors of its long divisions
 * included), so the values are the ones validated on hardware. */

/* x axis: VCO frequencies, one curve per v2i point */
static const uint64_t dg2_curve_freq_hz[2][8] = {
	{ 2500000000ULL, 3000000000ULL, 3000000000ULL, 3500000000ULL, 3500000000ULL,
	  4000000000ULL, 4000000000ULL, 5000000000ULL },
	{ 4000000000ULL, 4600000000ULL, 4601000000ULL, 5400000000ULL, 5401000000ULL,
	  6600000000ULL, 6601000000ULL, 8001000000ULL }
};

/* y axis heights, times 1000000000 */
static const uint64_t dg2_curve_0[2][8] = {
	{ 34149871, 39803269, 36034544, 40601014, 35646940, 40016109, 35127987, 41889522 },
	{ 70000000, 78770454, 70451838, 80427119, 70991400, 84230173, 72945921, 87064218 }
};

/* times 100 */
static const uint64_t dg2_curve_1[2][8] = {
	{ 85177000000000ULL, 79385227160000ULL, 95672603580000ULL, 88857207160000ULL,
	  109379790900000ULL, 103528193900000ULL, 131941242400000ULL, 117279000000000ULL },
	{ 60255000000000ULL, 55569000000000ULL, 72036000000000ULL, 69509000000000ULL,
	  81785000000000ULL, 731030000000000ULL, 96591000000000ULL, 69077000000000ULL }
};

/* times 1000000000000 */
static const uint64_t dg2_curve_2[2][8] = {
	{ 2186930000ULL, 2835287134ULL, 2395395343ULL, 2932270687ULL, 2351887545ULL,
	  2861031697ULL, 2294149152ULL, 3091730000ULL },
	{ 4560000000ULL, 5570000000ULL, 4610000000ULL, 5770000000ULL, 4670000000ULL,
	  6240000000ULL, 4890000000ULL, 6600000000ULL }
};

#define SNPS_HDMI_4999MHZ 4999999900ULL
#define SNPS_HDMI_9999MHZ (2 * SNPS_HDMI_4999MHZ)
#define SNPS_HDMI_16GHZ 16000000000ULL
#define SNPS_CURVE0_MULTIPLIER 1000000000ULL
#define SNPS_CURVE1_MULTIPLIER 100ULL
#define SNPS_CURVE2_MULTIPLIER 1000000000000ULL

static int ilog2_u64(uint64_t v)
{
	return v ? 63 - __builtin_clzll(v) : 0;
}

/* A division whose divisor the sequence takes as 32 bits. */
static uint64_t div_u64_by_u32(uint64_t n, uint64_t base)
{
	uint32_t b = (uint32_t)base;
	return b ? n / b : 0;
}

/* Rounding-up division in wrapping 64-bit arithmetic. */
static uint64_t div_round_up_u64(uint64_t n, uint64_t d)
{
	return d ? (n + d - 1) / d : 0;
}

static uint64_t isqrt_u64(uint64_t x)
{
	uint64_t r = 0, bit = 1ULL << 62;

	while (bit > x)
		bit >>= 2;
	while (bit) {
		if (x >= r + bit) {
			x -= r + bit;
			r = (r >> 1) + bit;
		} else {
			r >>= 1;
		}
		bit >>= 2;
	}
	return r;
}

/* Linear interpolation between two curve points, the slope in 1/100000
 * steps (two's-complement wrapping, as the sequence computes it). */
static uint64_t snps_interp(uint64_t x, uint64_t x1, uint64_t x2, uint64_t y1, uint64_t y2)
{
	uint64_t dydx = div_round_up_u64((y2 - y1) * 100000ULL, x2 - x1);
	return y1 + div_round_up_u64(dydx * (x - x1), 100000ULL);
}

static void snps_ana_cp(uint64_t vco_clk, uint32_t refclk_postscalar, int mpll_ana_v2i,
			int c, int a, uint32_t *ana_cp_int, uint32_t *ana_cp_prop)
{
	uint64_t vco_div_refclk_float, c0, c1, c2, temp;
	uint64_t c2_scaled1, c2_scaled2, svd1, svd2, adj1, adj2, cp_int, cp_prop;
	uint64_t c2_scaled_int, product, sq;

	vco_div_refclk_float = vco_clk * (1000000000000ULL / refclk_postscalar);

	/* the curves at the VCO frequency */
	c0 = snps_interp(vco_clk, dg2_curve_freq_hz[c][a], dg2_curve_freq_hz[c][a + 1],
			 dg2_curve_0[c][a], dg2_curve_0[c][a + 1]);
	c2 = snps_interp(vco_clk, dg2_curve_freq_hz[c][a], dg2_curve_freq_hz[c][a + 1],
			 dg2_curve_2[c][a], dg2_curve_2[c][a + 1]);
	c1 = snps_interp(vco_clk, dg2_curve_freq_hz[c][a], dg2_curve_freq_hz[c][a + 1],
			 dg2_curve_1[c][a], dg2_curve_1[c][a + 1]);
	c1 = c1 / SNPS_CURVE1_MULTIPLIER;

	/* curve 2 scaled by v2i, for the integral and the proportional part */
	temp = c2 * (uint64_t)(4 - mpll_ana_v2i);
	c2_scaled1 = temp / 16000;
	c2_scaled2 = temp / 160;

	/* the integral gain */
	svd1 = 112008301ULL * (vco_div_refclk_float / 100000);
	adj1 = SNPS_CURVE2_MULTIPLIER *
	       div_u64_by_u32(svd1, c0 * (c1 / SNPS_CURVE0_MULTIPLIER));
	cp_int = div_round_closest_u64(div_u64_by_u32(adj1, c2_scaled1), SNPS_CURVE2_MULTIPLIER);
	cp_int = cp_int < 1 ? 1 : cp_int > 127 ? 127 : cp_int;
	*ana_cp_int = (uint32_t)cp_int;

	/* the proportional gain */
	c2_scaled_int = c2_scaled1 * cp_int;
	product = c1 * (c2_scaled_int * (c0 / SNPS_CURVE0_MULTIPLIER));
	sq = isqrt_u64(div_round_up_u64(product, vco_div_refclk_float) *
		       (1000000000000ULL / 55));
	svd2 = (vco_div_refclk_float + 1000000 - 1) / 1000000;
	adj2 = 1460281ULL * div_round_up_u64(sq * svd2, c1);
	cp_prop = div_round_up_u64(adj2, c2_scaled2);
	cp_prop = cp_prop < 1 ? 1 : cp_prop > 127 ? 127 : cp_prop;
	*ana_cp_prop = (uint32_t)cp_prop;
}

static void mpllb_compute_hdmi(struct mpllb_state *s, uint64_t pixel_clock)
{
	const uint32_t refclk = 100000000, prescaler_divider = 1, ref_range = 3;
	const uint32_t ana_cp_int_gs = 64, ana_cp_prop_gs = 124;
	const uint32_t ssc_up_spread = 1, mpll_div5_en = 1, hdmi_div = 1;
	uint64_t datarate = pixel_clock * 10000;
	uint32_t refclk_postscalar = refclk >> prescaler_divider;
	uint32_t tx_clk_div, vco_div_refclk_integer, vco_div_refclk_fracn;
	uint32_t fracn_quot, fracn_rem, fracn_den, fracn_en, pmix_en, multiplier;
	uint32_t ana_cp_int, ana_cp_prop;
	uint64_t vco_clk, vco_rem;
	int mpll_ana_v2i, ana_freq_vco = 0, c, a = 0;

	/* the v2i point by data rate */
	if (datarate <= SNPS_HDMI_9999MHZ) {
		mpll_ana_v2i = 2;
		tx_clk_div = (uint32_t)ilog2_u64(SNPS_HDMI_9999MHZ / datarate);
	} else {
		mpll_ana_v2i = 3;
		tx_clk_div = (uint32_t)ilog2_u64(SNPS_HDMI_16GHZ / datarate);
	}
	vco_clk = (datarate << tx_clk_div) >> 1;

	vco_div_refclk_integer = (uint32_t)(vco_clk / refclk_postscalar);
	vco_rem = vco_clk % refclk_postscalar;
	/* From here on the sequence works with the quotient of that division
	 * in place of the VCO frequency (the band and the charge-pump curves
	 * are evaluated on it). */
	vco_clk = vco_clk / refclk_postscalar;
	vco_div_refclk_fracn = (uint32_t)((vco_rem << 32) / refclk_postscalar);

	fracn_quot = vco_div_refclk_fracn >> 16;
	fracn_rem = vco_div_refclk_fracn & 0xffff;
	fracn_rem = fracn_rem - (fracn_rem >> 15);
	fracn_den = 0xffff;
	fracn_en = (fracn_quot != 0 || fracn_rem != 0) ? 1 : 0;
	pmix_en = fracn_en;
	multiplier = (vco_div_refclk_integer - 16) * 2;

	/* one curve per v2i range; find the segment */
	c = mpll_ana_v2i - 2;
	for (int i = 0; i < 8; i += 2) {
		if (vco_clk <= dg2_curve_freq_hz[c][i + 1]) {
			a = i;
			ana_freq_vco = 3 - (a >> 1);
			break;
		}
	}
	snps_ana_cp(vco_clk, refclk_postscalar, mpll_ana_v2i, c, a, &ana_cp_int, &ana_cp_prop);

	mm_memset(s, 0, sizeof(*s));
	s->clock = (uint32_t)pixel_clock;
	s->ref_control = SNPS_PHY_REF_CONTROL_REF_RANGE(ref_range);
	s->mpllb_cp = SNPS_PHY_MPLLB_CP_INT(ana_cp_int) | SNPS_PHY_MPLLB_CP_PROP(ana_cp_prop) |
		      SNPS_PHY_MPLLB_CP_INT_GS(ana_cp_int_gs) |
		      SNPS_PHY_MPLLB_CP_PROP_GS(ana_cp_prop_gs);
	s->mpllb_div = (mpll_div5_en ? SNPS_PHY_MPLLB_DIV5_CLK_EN : 0) |
		       SNPS_PHY_MPLLB_TX_CLK_DIV(tx_clk_div) |
		       (pmix_en ? SNPS_PHY_MPLLB_PMIX_EN : 0) | SNPS_PHY_MPLLB_V2I(mpll_ana_v2i) |
		       SNPS_PHY_MPLLB_FREQ_VCO(ana_freq_vco);
	s->mpllb_div2 = SNPS_PHY_MPLLB_REF_CLK_DIV(prescaler_divider) |
			SNPS_PHY_MPLLB_MULTIPLIER(multiplier) | SNPS_PHY_MPLLB_HDMI_DIV(hdmi_div);
	s->mpllb_fracn1 = SNPS_PHY_MPLLB_FRACN_CGG_UPDATE_EN |
			  (fracn_en ? SNPS_PHY_MPLLB_FRACN_EN : 0) |
			  SNPS_PHY_MPLLB_FRACN_DEN(fracn_den);
	s->mpllb_fracn2 = SNPS_PHY_MPLLB_FRACN_QUOT(fracn_quot) | SNPS_PHY_MPLLB_FRACN_REM(fracn_rem);
	s->mpllb_sscen = ssc_up_spread ? SNPS_PHY_MPLLB_SSC_UP_SPREAD : 0;
}

/* ---- choosing settings -------------------------------------------------------------- */

static const struct mpllb_state *table_find(const struct mpllb_state *const *t, uint32_t clock)
{
	for (; *t; t++)
		if ((*t)->clock == clock)
			return *t;
	return NULL;
}

static void mirror_dpll(struct i915_device *i915, int port, const struct dg2_port_pll *p)
{
	struct intel_dpll_state *d;

	if (port < 0 || port >= INTEL_MAX_DPLLS)
		return;
	d = &i915->display.dpll[port];
	d->in_use = p->in_use;
	d->is_hdmi = p->in_use && !p->is_dp;
	d->ssc = p->in_use && !!(p->st.mpllb_sscen & SNPS_PHY_MPLLB_SSC_EN);
	d->link_rate_khz = p->in_use ? p->port_clock : 0;
}

int dg2_phy_rate_supported(struct i915_device *i915, int port, uint32_t link_rate_khz)
{
	(void)i915;
	if (!port_ok(port) || dp_is_uhbr(link_rate_khz))
		return 0;
	/* the embedded-panel list is the DisplayPort one plus the eDP rates */
	return table_find(dg2_edp_tables, link_rate_khz) != NULL;
}

uint32_t dg2_phy_max_link_rate(struct i915_device *i915, const struct intel_output *o)
{
	(void)i915;
	return o && o->is_edp ? 810000 : 1350000;
}

int dg2_phy_pll_get_dp(struct i915_device *i915, struct intel_output *o,
		       uint32_t link_rate_khz, int ssc)
{
	struct dg2_port_pll *p;
	const struct mpllb_state *e;
	const char *name;

	if (!o || !port_ok(o->port))
		return -EINVAL;
	name = intel_port_name(i915, o->port);
	e = table_find(o->is_edp ? dg2_edp_tables : dg2_dp_100_tables, link_rate_khz);
	if (!e) {
		kprintf("[drm] i915: port %s: no PHY PLL settings for DP at %u kHz\n", name,
			link_rate_khz);
		return -EINVAL;
	}
	p = &dg2_pll[o->port];
	mm_memset(p, 0, sizeof(*p));
	mm_memcpy(&p->st, e, sizeof(p->st));
	p->is_dp = 1;
	p->ssc_asked = !!ssc;
	p->port_clock = mpllb_port_clock(&p->st);
	p->in_use = 1;
	mirror_dpll(i915, o->port, p);
	i915_dbg("[drm] i915: port %s: PHY PLL for DP at %u kHz%s\n", name, p->port_clock,
		 (p->st.mpllb_sscen & SNPS_PHY_MPLLB_SSC_EN) ? " with SSC" : "");
	return o->port;
}

int dg2_phy_pll_get_hdmi(struct i915_device *i915, struct intel_output *o, uint32_t clock_khz)
{
	struct dg2_port_pll *p;
	const struct mpllb_state *e;
	const char *name;

	if (!o || !port_ok(o->port) || !clock_khz)
		return -EINVAL;
	name = intel_port_name(i915, o->port);
	p = &dg2_pll[o->port];
	mm_memset(p, 0, sizeof(*p));
	/* the tables first; the computed values are correct but not tuned */
	e = table_find(dg2_hdmi_tables, clock_khz);
	if (e)
		mm_memcpy(&p->st, e, sizeof(p->st));
	else
		mpllb_compute_hdmi(&p->st, clock_khz);
	p->is_dp = 0;
	p->port_clock = mpllb_port_clock(&p->st);
	/* computed settings land within a kHz; anything further off than
	 * half a percent is not the clock the sink was promised */
	if ((p->port_clock > clock_khz ? p->port_clock - clock_khz : clock_khz - p->port_clock) >
	    clock_khz / 200) {
		kprintf("[drm] i915: port %s: PHY PLL for TMDS %u kHz would run at %u kHz\n", name,
			clock_khz, p->port_clock);
		mm_memset(p, 0, sizeof(*p));
		return -EINVAL;
	}
	p->in_use = 1;
	mirror_dpll(i915, o->port, p);
	i915_dbg("[drm] i915: port %s: PHY PLL for TMDS %u kHz (%s, asked %u)\n", name,
		 p->port_clock, e ? "table" : "computed", clock_khz);
	return o->port;
}

int dg2_phy_hdmi_clock_ok(struct i915_device *i915, const struct intel_output *o,
			  uint32_t clock_khz)
{
	struct mpllb_state st;
	uint32_t got;

	(void)i915;
	if (!o || !port_ok(o->port) || !clock_khz)
		return 0;
	if (table_find(dg2_hdmi_tables, clock_khz))
		return 1;
	/* computed settings: the same half-percent bound as when the PLL
	 * is taken (dg2_phy_pll_get_hdmi()) */
	mm_memset(&st, 0, sizeof(st));
	mpllb_compute_hdmi(&st, clock_khz);
	got = mpllb_port_clock(&st);
	return (got > clock_khz ? got - clock_khz : clock_khz - got) <= clock_khz / 200;
}

void dg2_phy_pll_put(struct i915_device *i915, int pll)
{
	if (!port_ok(pll))
		return;
	dg2_pll[pll].in_use = 0;
	mirror_dpll(i915, pll, &dg2_pll[pll]);
}

/* ---- enabling and disabling the PLL ------------------------------------------------- */

static int pll_running(struct i915_device *i915, int phy)
{
	return !!(i915_read32(i915, DG2_PLL_ENABLE(phy)) & DG2_PLL_ENABLE_BIT);
}

static void mpllb_disable(struct i915_device *i915, int phy, const char *name)
{
	uint32_t enable_reg = DG2_PLL_ENABLE(phy);

	/* 1. The voltage change before a frequency change is the CDCLK
	 * code's business. */
	/* 2. PLL enable off. */
	rmw(i915, enable_reg, DG2_PLL_ENABLE_BIT, 0);
	/* 4. The force off: the PLL may stop now. */
	rmw(i915, SNPS_PHY_MPLLB_DIV(phy), SNPS_PHY_MPLLB_FORCE_EN, 0);
	/* 5. The PHY acknowledges by dropping the lock. */
	if (wait_reg(i915, enable_reg, DG2_PLL_LOCK, 0, 5000))
		kprintf("[drm] i915: port %s: PHY PLL still locked after being disabled\n", name);
}

static int mpllb_enable(struct i915_device *i915, int phy, const struct mpllb_state *s,
			const char *name)
{
	uint32_t enable_reg = DG2_PLL_ENABLE(phy);

	/* 3. The PLL's words for the frequency. */
	i915_write32(i915, SNPS_PHY_MPLLB_CP(phy), s->mpllb_cp);
	i915_write32(i915, SNPS_PHY_MPLLB_DIV(phy), s->mpllb_div);
	i915_write32(i915, SNPS_PHY_MPLLB_DIV2(phy), s->mpllb_div2);
	i915_write32(i915, SNPS_PHY_MPLLB_SSCEN(phy), s->mpllb_sscen);
	i915_write32(i915, SNPS_PHY_MPLLB_SSCSTEP(phy), s->mpllb_sscstep);
	i915_write32(i915, SNPS_PHY_MPLLB_FRACN1(phy), s->mpllb_fracn1);
	i915_write32(i915, SNPS_PHY_MPLLB_FRACN2(phy), s->mpllb_fracn2);

	/* 4. A voltage change for the frequency is the CDCLK code's. */

	/* 5. PLL enable on. */
	rmw(i915, enable_reg, 0, DG2_PLL_ENABLE_BIT);

	/* 9. The force on, which keeps the PLL running through the lane
	 * programming.  Not before the enable: that would start the PLL
	 * before it has sampled the dividers. */
	i915_write32(i915, SNPS_PHY_MPLLB_DIV(phy), s->mpllb_div | SNPS_PHY_MPLLB_FORCE_EN);

	/* 10. The lock, sampled from the PHY's PLL state. */
	if (wait_reg(i915, enable_reg, DG2_PLL_LOCK, DG2_PLL_LOCK, 5000)) {
		kprintf("[drm] i915: port %s: PHY PLL not locked (enable %08x)\n", name,
			i915_read32(i915, enable_reg));
		return -ETIMEDOUT;
	}
	/* 11. The voltage after a frequency change: the CDCLK code's. */
	return 0;
}

int dg2_phy_pll_enable(struct i915_device *i915, struct intel_output *o, int lanes)
{
	struct dg2_port_pll *p;
	const char *name;
	int phy, rc;

	if (!o || !port_ok(o->port))
		return -EINVAL;
	phy = dg2_port_to_phy(o->port);
	name = intel_port_name(i915, o->port);
	p = &dg2_pll[o->port];
	if (!p->in_use) {
		kprintf("[drm] i915: port %s: PHY PLL enabled without settings\n", name);
		return -EINVAL;
	}
	if (lanes < 1 || lanes > 4)
		lanes = 4;
	p->lanes = lanes;
	/* A PLL the firmware left running is taken down first: its dividers
	 * are sampled only when it starts. */
	if (pll_running(i915, phy))
		mpllb_disable(i915, phy, name);
	rc = mpllb_enable(i915, phy, &p->st, name);
	i915_dbg("[drm] i915: port %s: PHY %c PLL %s at %u kHz: enable %08x div %08x div2 %08x\n",
		 name, 'A' + phy, rc ? "failed" : "on", p->port_clock,
		 i915_read32(i915, DG2_PLL_ENABLE(phy)), i915_read32(i915, SNPS_PHY_MPLLB_DIV(phy)),
		 i915_read32(i915, SNPS_PHY_MPLLB_DIV2(phy)));
	return rc;
}

void dg2_phy_pll_disable(struct i915_device *i915, struct intel_output *o)
{
	int phy;

	if (!o || !port_ok(o->port))
		return;
	phy = dg2_port_to_phy(o->port);
	mpllb_disable(i915, phy, intel_port_name(i915, o->port));
}

/* ---- reading back what runs -------------------------------------------------------- */

static void mpllb_readout(struct i915_device *i915, int phy, struct mpllb_state *s)
{
	s->mpllb_cp = i915_read32(i915, SNPS_PHY_MPLLB_CP(phy));
	s->mpllb_div = i915_read32(i915, SNPS_PHY_MPLLB_DIV(phy));
	s->mpllb_div2 = i915_read32(i915, SNPS_PHY_MPLLB_DIV2(phy));
	s->mpllb_sscen = i915_read32(i915, SNPS_PHY_MPLLB_SSCEN(phy));
	s->mpllb_sscstep = i915_read32(i915, SNPS_PHY_MPLLB_SSCSTEP(phy));
	s->mpllb_fracn1 = i915_read32(i915, SNPS_PHY_MPLLB_FRACN1(phy));
	s->mpllb_fracn2 = i915_read32(i915, SNPS_PHY_MPLLB_FRACN2(phy));
	/* The range field is the firmware's; only that one documented
	 * field is kept, for checking. */
	s->ref_control = i915_read32(i915, SNPS_PHY_REF_CONTROL(phy)) &
			 SNPS_PHY_REF_CONTROL_REF_RANGE_MASK;
	/* The divider word was written twice, the second time with the force
	 * bit: the state proper is without it. */
	s->mpllb_div &= ~SNPS_PHY_MPLLB_FORCE_EN;
	s->clock = mpllb_port_clock(s);
}

uint32_t dg2_phy_port_link_rate(struct i915_device *i915, struct intel_output *o)
{
	struct mpllb_state s;
	uint32_t en;
	int phy;

	if (!o || !port_ok(o->port))
		return 0;
	phy = dg2_port_to_phy(o->port);
	en = i915_read32(i915, DG2_PLL_ENABLE(phy));
	if (!(en & DG2_PLL_ENABLE_BIT) || !(en & DG2_PLL_LOCK))
		return 0;
	mpllb_readout(i915, phy, &s);
	i915_dbg("[drm] i915: port %s: firmware PHY PLL at %u kHz (div %08x div2 %08x fracn %08x/%08x ref %08x)\n",
		 intel_port_name(i915, o->port), s.clock, s.mpllb_div, s.mpllb_div2,
		 s.mpllb_fracn1, s.mpllb_fracn2, s.ref_control);
	return s.clock;
}

/* ---- signal levels -------------------------------------------------------------------- */

void dg2_phy_set_signal_level(struct i915_device *i915, struct intel_output *o, int level)
{
	const struct snps_trans *t;
	int n, phy;
	uint32_t clock;

	if (!o || !port_ok(o->port))
		return;
	phy = dg2_port_to_phy(o->port);
	clock = o->link_rate_khz ? o->link_rate_khz : dg2_pll[o->port].port_clock;

	if (output_is_dp(o) && dp_is_uhbr(clock)) {
		t = dg2_snps_trans_uhbr;
		n = ARRAY_LEN(dg2_snps_trans_uhbr);
		if (level < 0)
			level = 0;
	} else {
		t = dg2_snps_trans;
		n = ARRAY_LEN(dg2_snps_trans);
		if (level < 0)
			level = output_is_dp(o) ? 0 : DG2_SNPS_TRANS_HDMI_DEFAULT;
	}
	if (level >= n)
		level = n - 1;

	/* Every lane gets the level: the link trains all of them alike. */
	for (int ln = 0; ln < 4; ln++) {
		uint32_t v = SNPS_PHY_TX_EQ_MAIN(t[level].vswing) |
			     SNPS_PHY_TX_EQ_PRE(t[level].pre_cursor) |
			     SNPS_PHY_TX_EQ_POST(t[level].post_cursor);
		i915_write32(i915, SNPS_PHY_TX_EQ(ln, phy), v);
	}
	i915_dbg("[drm] i915: port %s: PHY levels: entry %d (swing %u, pre %u, post %u)\n",
		 intel_port_name(i915, o->port), level, t[level].vswing, t[level].pre_cursor,
		 t[level].post_cursor);
}

void dg2_phy_psr_power_state(struct i915_device *i915, struct intel_output *o, int enable)
{
	int phy;

	if (!o || !port_ok(o->port))
		return;
	phy = dg2_port_to_phy(o->port);
	rmw(i915, SNPS_PHY_TX_REQ(phy), SNPS_PHY_TX_REQ_LN_DIS_PWR_STATE_PSR_MASK,
	    SNPS_PHY_TX_REQ_LN_DIS_PWR_STATE_PSR(enable ? 2 : 3));
}

/* ---- the port buffer ----------------------------------------------------------------- */

void dg2_ddi_buf_enable(struct i915_device *i915, struct intel_output *o, int lanes)
{
	uint32_t buf_ctl = 0;
	int is_dp;

	if (!o || !port_ok(o->port))
		return;
	is_dp = output_is_dp(o);
	if (lanes < 1 || lanes > 4)
		lanes = is_dp ? (o->lane_count ? o->lane_count : 4) : 4;

	/* The level was the PHY's to set; the buffer's translation select
	 * stays at 0.  DisplayPort names its width; for HDMI the width and
	 * the levels in the buffer are ignored.  No port here shares its
	 * lanes, so there is no four-lane strap to keep, and there is no
	 * Type-C ownership or lane staggering: the Type-C DDI of this part
	 * is a fixed connector on a Synopsys PHY. */
	if (o->lane_reversal)
		buf_ctl |= DDI_BUF_PORT_REVERSAL;
	if (is_dp)
		buf_ctl |= DDI_PORT_WIDTH((uint32_t)lanes) | DDI_BUF_TRANS_SELECT(0);
	i915_write32(i915, DDI_BUF_CTL(o->port), buf_ctl | DDI_BUF_CTL_ENABLE);
	(void)i915_read32(i915, DDI_BUF_CTL(o->port));
	/* The buffer leaves idle within 1.2 ms on this part; 10 are given. */
	if (wait_reg(i915, DDI_BUF_CTL(o->port), DDI_BUF_IS_IDLE, 0, 10000))
		kprintf("[drm] i915: port %s: buffer did not become active\n",
			intel_port_name(i915, o->port));
	i915_dbg("[drm] i915: port %s: buffer on, %d lanes: DDI_BUF_CTL %08x\n",
		 intel_port_name(i915, o->port), lanes, i915_read32(i915, DDI_BUF_CTL(o->port)));
}

void dg2_ddi_buf_disable(struct i915_device *i915, struct intel_output *o)
{
	if (!o || !port_ok(o->port))
		return;
	if (!(i915_read32(i915, DDI_BUF_CTL(o->port)) & DDI_BUF_CTL_ENABLE))
		return;
	rmw(i915, DDI_BUF_CTL(o->port), DDI_BUF_CTL_ENABLE, 0);
	/* Before display version 14 the idle wait comes after the transport
	 * control is off; the caller turns that off next, and the buffer
	 * reports idle within the same 10 ms either way. */
	if (wait_reg(i915, DDI_BUF_CTL(o->port), DDI_BUF_IS_IDLE, DDI_BUF_IS_IDLE, 10000))
		kprintf("[drm] i915: port %s: buffer did not go idle\n",
			intel_port_name(i915, o->port));
}

/* ---- once at display init ------------------------------------------------------------ */

/* Every table entry produces the clock it is listed for, and so do the
 * computed HDMI settings for the HDMI entries' clocks. */
static void verify_tables(void)
{
	static const struct mpllb_state *const *const all[] = {
		dg2_dp_100_tables, dg2_edp_tables, dg2_hdmi_tables,
	};
	int bad = 0;

	for (int i = 0; i < ARRAY_LEN(all); i++) {
		for (const struct mpllb_state *const *t = all[i]; *t; t++) {
			uint32_t clk = mpllb_port_clock(*t);
			if (!clock_matches(clk, (*t)->clock)) {
				kprintf("[drm] i915: PHY PLL table entry for %u kHz gives %u kHz\n",
					(*t)->clock, clk);
				bad++;
			}
			if (all[i] == dg2_hdmi_tables) {
				struct mpllb_state s;
				mpllb_compute_hdmi(&s, (*t)->clock);
				clk = mpllb_port_clock(&s);
				if (!clock_matches(clk, (*t)->clock)) {
					kprintf("[drm] i915: computed PHY PLL for %u kHz gives %u kHz\n",
						(*t)->clock, clk);
					bad++;
				}
			}
		}
	}
	if (!bad)
		i915_dbg("[drm] i915: DG2 PHY PLL tables check out\n");
}

/* The PHYs calibrate and adapt their transmitters at power-up; each
 * transmitter's acknowledge bit stays set until that is done.  Waited
 * for once the display core is up and before any port is used; a PHY
 * that does not finish within 25 ms is remembered and driven anyway. */
static void wait_for_calibration(struct i915_device *i915)
{
	for (int phy = SNPS_PHY_A; phy < SNPS_NUM_PHYS; phy++) {
		if (wait_reg(i915, DG2_PHY_MISC(phy), DG2_PHY_DP_TX_ACK_MASK, 0, 25000) == 0)
			continue;
		dg2_calib_failed |= 1u << phy;
		kprintf("[drm] i915: PHY %c did not finish calibrating (misc %08x); its port is driven anyway\n",
			'A' + phy, i915_read32(i915, DG2_PHY_MISC(phy)));
	}
}

int dg2_phy_init(struct i915_device *i915)
{
	static const int ports[SNPS_NUM_PHYS] = {
		DG2_PORT_A, DG2_PORT_B, DG2_PORT_C, DG2_PORT_D_XELPD, DG2_PORT_TC1,
	};

	mm_memset(dg2_pll, 0, sizeof(dg2_pll));
	dg2_calib_failed = 0;

	verify_tables();
	wait_for_calibration(i915);

	for (int i = 0; i < SNPS_NUM_PHYS; i++) {
		int phy = dg2_port_to_phy(ports[i]);
		uint32_t en = i915_read32(i915, DG2_PLL_ENABLE(phy));
		uint32_t ref = i915_read32(i915, SNPS_PHY_REF_CONTROL(phy)) &
			       SNPS_PHY_REF_CONTROL_REF_RANGE_MASK;

		i915_dbg("[drm] i915: port %s (PHY %c): PLL enable %08x, misc %08x, ref range %u, DDI_BUF_CTL %08x\n",
			 intel_port_name(i915, ports[i]), 'A' + phy, en,
			 i915_read32(i915, DG2_PHY_MISC(phy)), ref >> 27,
			 i915_read32(i915, DDI_BUF_CTL(ports[i])));
		/* Every table is for the firmware's reference range; a PHY in
		 * another one would run its port at the wrong rate. */
		if (ref && ref != SNPS_PHY_REF_CONTROL_REF_RANGE(3))
			kprintf("[drm] i915: PHY %c: reference range %u, the PLL tables expect 3\n",
				'A' + phy, ref >> 27);
	}
	return 0;
}
